<?php

namespace PatientBundle\Repository;

/**
 * metueleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class metueleRepository extends \Doctrine\ORM\EntityRepository
{
}
